Update gke-deployment.yml

diff --git a/.github/workflows/gke-deployment.yml b/.github/workflows/gke-deployment.yml
--- a/.github/workflows/gke-deployment.yml
+++ b/.github/workflows/gke-deployment.yml
@@ -38,11 +38,18 @@ jobs:
              cd  /home/runner/work/github-actions/github-actions/temp
              terraform init 
              
+      - name: Activate Google Cloud service account
+        run: |
+             cd /home/runner/work/github-actions/github-actions/temp
+             gcloud auth activate-service-account --key-file=mvn-project/gcp-key.json
+             if [ $? -ne 0 ]; then
+              echo "Failed to activate service account."
+             exit 1
+              fi
+              
       - name: Terraform Plan
         run: |
              cd /home/runner/work/github-actions/github-actions/temp
-             gcloud auth activate-service-account
-             --key-file=mvn-project/gcp-key.json
              terraform plan
       
       - name: Terraform apply
